### ISSUE TITLE
GSM PCB

### ISSUE THREAD

**Issue by runeron** [mzst123/Xdrip-Lipo-Board#4]
First of all, thank you for this; excellent having a PCB to solder the components on.

Now that I have a working BLE receiver, I am planning to create a GSM receiver/[Parakeet](https://github.com/jamorham/wixel-xDrip/blob/parakeet-gsm-modem/README.md). What are the chances of you creating a modified version of this PCB where the HM11 is replaced by the SIM800L GSM module?

I would do it myself, but then I have to teach myself HOW first...

**Comment by mzst123** [comment]
Hi, it sure seems very easy. The only problem is that there is no footprint available. I do not have a SIM800L module. Can you measure the holes of the module and make a drawing? Then I can copy it into the program.
I need to do something like this so only the distances of the holes and the outline of the module are relevant. Regards
![tp4056 module](https://cloud.githubusercontent.com/assets/16510934/15784499/b0c4566e-29aa-11e6-8a05-74ac352b6b8c.png)

**Comment by runeron** [comment]
Outer dimension of module: 2.5 cm x 2.3 cm (Thickness is x 0.7 cm). The holes are made for pin headers w/2.5 mm pitch. Drawing is best effort..
![sim800l](https://cloud.githubusercontent.com/assets/3177490/15791790/bd39378c-29d9-11e6-98f1-7337ec182b2b.png)
Not sure how it would be solved to have it on the PCB, but since there are components on both sides, maybe just have holes for the 6 x 1 & 5 x 1 pin headers (2.5 mm pitch) on each side of the SIM800L board?

**Comment by mzst123** [comment]
Thanks i will see what i can come up with. Only one measurement is missing: the distance between the hole and the edge of the PCB.
![untitled](https://cloud.githubusercontent.com/assets/16510934/15802480/a504b286-2aab-11e6-95c0-6b06b9b27a35.png)

**Comment by runeron** [comment]
Nice.. It's 1,5 mm as far as I can measure.

Edit: The measurements in my earlier sketch was from center-hole. Just thought I'd mention it

**Comment by mzst123** [comment]
Hi, I just made this draft. Please print this out on an sheet of A4 paper. If you can, use a laser printer on maximum resolution setting. Then place the module on top an check if it fits. You can also stick the header pins into the paper and see if they fit. 
The sim tray is on the back (in contact with the paper).
Thanks
[SIM800L-.pdf](https://github.com/mzst123/Xdrip-Lipo-Board/files/303821/SIM800L-.pdf)

**Comment by runeron** [comment]
Amazing! I will try it out as soon as I get back from work today.

I did notice a potential challenge yesterday, though.. It doesn't look like the SIM800L will work with the 3.3V from Wixel (requires 3.4V~4.4V & 2A at peak):

![image](https://cloud.githubusercontent.com/assets/3177490/15887249/8a6cdba2-2d61-11e6-82c5-7e904d6ce6e0.png)

I did all the connections on my breadboard; just replacing the HM11 w/GSM, and was not able to communicate with it. After doing som more reading, it appears the Wixel is not able to wake up the SIM module.

I tried connecting the SIM800L directly to the powersource (first 500mAH, 3.7V Li Po (25C), then 2400mAH, 3.7V Li Ion battery) with no success. I think I might need another powersource, and I also think the SIM800L needs to be powered directly from source; I guess this would require additional modifications of the PCB.

It COULD be the simcard (provider/defect/etc), but ran out of time yesterday; I was also struggling with figuring out the meaning of the different the LED statuses I got. Will try more today if I manage to find the time, and will try powering w/batteries as suggested in jamorham's parakeet guide.

It is a bit more work than I thought.. Still; if you make the Eagle model of SIM800L that would be fantastic.. Then I can eventually try and make a PCB myself if this is too much work for you :)

**Comment by runeron** [comment]
Hi, and sorry for the delay!

I matched up the pins as best I could, and it looked like it was a perfect fit.

I've had a look at your eagle files, and I can order the parts and try this out whenever you feel it is ready. No problem if it doesn't work on the first try.

My only issue is deliverytime of PCB boards; I might need to find a quicker way of getting them made.

**Comment by mzst123** [comment]
Perfect. I made the board as a test. I still have to move some components for better access to the simcard, as i don't know how much space there will be to insert it. During next week it will be ready ;). I changed some of the components (lessons learned from the old board). Can you solder the smaller components?
If not, i could help you assembling the boards. I bought a hot air rework station, so let me know.

**Comment by runeron** [comment]
I did struggle a bit with a few components on the last board, but I am waiting for some solder paste now; hoping this will help..

Not sure how you could assist in assembling, as I live in Norway. Otherwise that would be great:)

**Comment by mzst123** [comment]
Well I could order the parts, assemble the boards and mail them to you. Its not a problem for me, however it will take a little longer.

**Comment by runeron** [comment]
Wow. That would be amazing.. I can transfer money for parts/work via paypal or whatever you prefer, if you pm me the details.

Edit: removed

Not sure how that is possible on github, so will leave my email here for now. :)
