### ISSUE TITLE
Parakeet

### ISSUE THREAD

**Issue by Deneil1983** [mzst123/Xdrip-Lipo-Board#5]
Hi have you had any joy getting the parakeet to work? I've ordered the parts but as yet not been able to older them all together, is there anyway you would be able to help me build the parakeet if I was to send you all the stuff. 

Thanks
Deneil

**Comment by mzst123** [comment]
Sure thing. It works. I can help you, no problem. Please contact me via e-mail

**Comment by Deneil1983** [comment]
Your a life saver, will email you now thanks

**Comment by Deneil1983** [comment]
Hi thank you so much for agreeing to help me get set up with the parakeet. What would be the best way for you to help me get set up? I send you what I already have or you make it and I cover the costs for materials? I'm ok with both suggestions.

Thanks once again 
Deneil xxx

Deneil Yates-Savage 💗

Wednesday, 3 August 2016, 2:16 pm +0100 from notifications@github.com  notifications@github.com:

**Comment by Deneil1983** [comment]
Hi can you send.me.your email address xxx

**Comment by mzst123** [comment]
Hi, i think it is easier if you send me what you already have.

**Comment by Deneil1983** [comment]
Email sent thank you so much
