### ISSUE TITLE
Enclosure - different size batteries?

### ISSUE THREAD

**Issue by whoiswes** [mzst123/Xdrip-Lipo-Board#7]
mzst123,

First, thank you for putting both the PCB and enclosure projects together - I have built 2 boards so far and they have performed fantasic!

I do however wonder if it would be possible to have additional enclosures designed for larger batteries.  Currently I'm using a 2000 mAh battery from adafruit in a tic-tac case.  It's functional, but larger.  I'd be happy to design a case around the larger battery size, but am unsure where to start in terms of design tools  I have zero 3D printing experience.

My apologies for putting this on the bug tracker as a discussion rather than an actual bug, but hopefully this will spawn some useful discussion, if nothing else.

Again, thank you so much for making this available

Wes

**Comment by mzst123** [comment]
Hi, i used the free program "Autodesk Fusion 360" to design the cases but im sure there are better ways to do it. It works but has some annoyances. I also had no experience in 3D design before. I made an updated version from the mistakes learned (but with same size battery) that i haven't published yet. The biggest problem I encountered was with the tolerances of the material/printer. Another issue was the closing mecanism which is not possible to do reliably with the material i used (PLA) so now i just close it with some adhesive tape.
I can upload the files if you want.
Regards
