### ISSUE TITLE
Version V2.1

### ISSUE THREAD

**Issue by d3xr** [mzst123/Xdrip-Lipo-Board#8]
Hi! Where I can find Xdrip PCB Lipo Board V2.1 files?

**Comment by mzst123** [comment]
Hi, the files are [here](https://github.com/mzst123/Xdrip-Lipo-Board/tree/master/Eagle%20PCB%20Files). you can also order them directly from [OSHPark](https://oshpark.com/shared_projects/IuYnoGB9). Regards
