### ISSUE TITLE
Help from an expert needed

### ISSUE THREAD

**Issue by Stef-M** [mzst123/Xdrip-Lipo-Board#9]
Hi,
i've read about this wonderful project, and am very interested.
I'd like to ask you if you have considered to sell one (eg if you have one more circuit).
Unfortunately I'm not so expert for realizing one from scratch.

Many thanks in advance.

Best regards :)

**Comment by mzst123** [comment]
Hi, I think I should still have one or two at home. I will check and let you know tomorrow. Regards

**Comment by mzst123** [comment]
Hi @Stef-M 
I just checked and i still have parts to build at least one. Only the Bluetooth module is missing, but i could order it for you. Let me know if you are still interested.
Regards
